app:
  group: &appGroup "voyago"
  name: &appName "core-api"
  full_id: &fullID "voyago.core-api"
  env: "staging"
  version: "1.0.0"

http:
  port: 4000
  prefork: false
  read_timeout: 10 #in seconds
  write_timeout: 10 #in seconds
  idle_timeout: 30 #in seconds

telemetry:
  enabled: true
  type: "otel"  # Options: "datadog", "otel", or leave empty for no-op
  metrics_address: "127.0.0.1:4317"  # OTel Collector gRPC
  tracer_address: "127.0.0.1:4317"   # OTel Collector gRPC
  namespace: *fullID
  sample_rate: 1.0  # 1.0 = 100% sampling (all traces)

log:
  path: "./logs/api/app.log"
  level: 4
  rotation:
    max_size: 100 # in MB, before log is rotated
    max_backup: 10 # number of old log files to keep
    max_age: 14 # number of days to retain log files
    compress: true # backup log will compressed (zip)